---
apiVersion: v1
kind: Service
metadata:
  name: my-node-app
spec:
  type: LoadBalancer  # Use LoadBalancer for external access
  ports:
  - port: 80
    targetPort: 8080  # The port your app listens on
  selector:
    app: my-node-app